.Dd $Mdocdate$
.Dt DSBMC-Cli 1
.Os
.Sh NAME
.Nm dsbmc-cli
.Nd command-line client for DSBMD
.Sh SYNOPSIS
.Nm
.Fl L Ar event Ar command
.Op Ar arg ...
\;
.Op Fl L Ar ...
.Nm
.Fl a
.Bo
.Fl U Ar time
.Bc
.Bo
.Op Fl L Ar event Ar command Op Ar arg ...
\;
.Op Fl L Ar ...
.Bc
.Nm
.Brq Bro Fl e | u Brc Bo Fl f Bc | Bro Fl m | s | u | v Ar speed Brc
.Ar device
.Nm
.Brq Fl e | u
.Ar "<mount point>"
.Nm
.Fl i
.Ar "<disk image>"
.Nm
.Fl l
.Nm
.Op Fl h
.Sh DESCRIPTION
.Nm
is a command-line client for DSBMD that provides a simple interface
to query information about storage devices, and to send requests to
mount, unmount and eject these.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl L
Listen for
.Ar event ,
and execute the
.Ar command
every time the
.Em event
is received. Possible events are
.Em mount ,
.Em unmount ,
.Em add ,
and
.Em remove .
The
.Ar command
must be terminated by a semicolon
.Pq Sq \;
as a separate argument. Each event provides information about the device
that can be accessed using the placeholders
.Em %d
(device name),
.Em %l
(volume label),
.Em %m
(mount point) (only
.Em mount
and
.Em unmount
), and
.Em %t
(device type). A literal percent character
.Pq Sq %
must be escaped by a further
.Sq %
character
.Pq Dq %% .

Possible values for the device type
.Pq Em %t
are
.Em hdd , usbdisk , datacd , audiocd , dvd , vcd ,  svcd ,  mmc , mtp ,
and
.Em ptp .

The
.Fl L
option can be given multiple times.
.It Fl U
Auto-unmount. Try to unmount each automounted device every
.Ar time
seconds.
.It Fl a
Automount. After mounting all devices presented by DSBMD,
.Xr dsbmc-cli 1
waits for new devices added to the system, and mounts them.
In addition, the
.Fl L
option can be specified for each event. If
.Xr dsbmc-cli 1
automounts a device, it executes the command defined for the
.Em mount
event.
.It Fl e Ar device , Fl e Ar <mount point>
Eject the given
.Ar device
or the device mounted on
.Ar <mount point>
.It Fl i Ar <disk image>
Create a memory disk to access the given
.Ar disk image .
.It Fl l
List all currently attached devices DSBMD supports.
.It Fl m Ar device
Mount the given
.Ar device .
.It Fl s Ar device
The storage capacity of the given
.Ar device
is queried, and the media size, the number of used and free bytes are
printed to stdout.
.It Fl u Ar device , Fl u Ar <mount point>
Unmount the given
.Ar device
or the device mounted on
.Ar <mount point>
.It Fl v Ar speed Ar device
Set the reading speed of the given CD/DVD
.Ar device .
.Sh EXAMPLES
.Dl $ dsbmc-cli -L mount printf \(dq%%s was mounted on %%s\en\(dq %d %m ';'
.Dl $ dsbmc-cli -L add echo \(dqDevice %d of type %t was added.\(dq ';'

